// ==================================================
// Z-CANVAS — PHASE-15 HISTORY, SNAPSHOT & RECOVERY
// core/history/history_manager.dart
//
// PRIMARY ROLE: MASTER HISTORY ORCHESTRATOR
//
// OWNS:
//   ✔ Undo stack management (push, pop, trim)
//   ✔ Redo stack management (push, pop, clear)
//   ✔ History timeline — ordered immutable entry log
//   ✔ History entry registration per completed action
//   ✔ History limits enforcement (max size, eviction)
//   ✔ Snapshot coordination (before/after IDs linked to entries)
//   ✔ Recovery coordination (delegates to RecoveryEngine)
//   ✔ History report generation
//
// DOES NOT OWN:
//   ❌ Layer mutation  ❌ Canvas access  ❌ Render access
//   ❌ Action execution  ❌ UI access  ❌ Snapshot creation
//
// COMMUNICATION ALLOWED:
//   ✔ SnapshotEngineInterface  ✔ RecoveryEngineInterface
//   ✔ HistoryGuardInterface    ✔ EditorController (via callback)
//
// COMMUNICATION FORBIDDEN:
//   ❌ UI  ❌ Canvas  ❌ RenderEngine  ❌ LayerEngine (write)
// ==================================================

import 'dart:async';

import '../../controllers/action_router.dart' show ActionType, ActionSource;

// ==================================================
// DOWNSTREAM INTERFACE CONTRACTS
// HistoryManager depends only on these abstractions.
// Concrete implementations live in the other Phase-15 files.
// ==================================================

// — FILE-2 boundary —
abstract interface class SnapshotEngineInterface {
  /// Creates a new snapshot and returns its ID.
  Future<String> createSnapshot({required String sessionId});

  /// Validates an existing snapshot by ID.
  /// Returns true if the snapshot is intact and usable.
  Future<bool> validateSnapshot(String snapshotId);

  /// Removes a snapshot that is no longer referenced by any history entry.
  Future<void> removeSnapshot(String snapshotId);
}

// — FILE-3 boundary —
abstract interface class RecoveryEngineInterface {
  /// Restores the state captured in [snapshotId].
  /// Returns null on success or a failure reason string.
  Future<String?> restoreSnapshot(String snapshotId, {required String sessionId});

  /// Rolls back to the most recent safe snapshot if execution failed.
  /// Returns null on success or a failure reason string.
  Future<String?> recoverLatestSafeState({required String sessionId});
}

// — FILE-4 boundary —
abstract interface class HistoryGuardInterface {
  /// Returns true if an undo operation is safe to proceed.
  Future<bool> canUndo(HistoryEntry entry);

  /// Returns true if a redo operation is safe to proceed.
  Future<bool> canRedo(HistoryEntry entry);

  /// Returns true if registering [entry] is safe (no corruption risk).
  Future<bool> canRegister(HistoryEntry entry);
}

// ==================================================
// HISTORY ENTRY STATUS
// Tracks the lifecycle state of a recorded history entry.
// ==================================================

enum HistoryEntryStatus {
  /// Action completed and state committed successfully.
  committed,

  /// Action was undone — entry sits on the redo stack.
  undone,

  /// Action was redone — entry re-pushed to the undo stack.
  redone,

  /// Action failed during execution; snapshot may be partial.
  failed,

  /// Entry was rolled back by the safety/recovery system.
  rolledBack,

  /// Entry was evicted by history limit enforcement (trimHistory).
  evicted,
}

// ==================================================
// HISTORY ENTRY
// Immutable record of a single completed action.
// Written once; status field is updated via [copyWith] for state transitions.
// ==================================================

class HistoryEntry {
  const HistoryEntry({
    required this.historyId,
    required this.actionId,
    required this.actionType,
    required this.timestamp,
    required this.source,
    required this.status,
    this.beforeSnapshotId,
    this.afterSnapshotId,
    this.description,
  });

  /// Unique ID for this history record (generated by HistoryManager).
  final String historyId;

  /// commandId from Phase-13 / sessionId from Phase-14.
  final String actionId;

  final ActionType          actionType;
  final DateTime            timestamp;
  final ActionSource        source;
  final HistoryEntryStatus  status;

  /// Snapshot ID captured before this action executed.
  final String? beforeSnapshotId;

  /// Snapshot ID captured after this action executed successfully.
  final String? afterSnapshotId;

  /// Human-readable description for history report / UI tooltip.
  final String? description;

  HistoryEntry copyWith({HistoryEntryStatus? status}) => HistoryEntry(
        historyId:        historyId,
        actionId:         actionId,
        actionType:       actionType,
        timestamp:        timestamp,
        source:           source,
        status:           status ?? this.status,
        beforeSnapshotId: beforeSnapshotId,
        afterSnapshotId:  afterSnapshotId,
        description:      description,
      );

  @override
  String toString() =>
      'HistoryEntry(id: $historyId, action: $actionType, '
      'status: $status, ts: ${timestamp.toIso8601String()})';
}

// ==================================================
// REGISTRATION PARAMS
// Input contract for registerAction() — avoids long positional arg lists.
// ==================================================

class HistoryRegistrationParams {
  const HistoryRegistrationParams({
    required this.actionId,
    required this.actionType,
    required this.source,
    this.beforeSnapshotId,
    this.afterSnapshotId,
    this.description,
    this.status = HistoryEntryStatus.committed,
  });

  final String            actionId;
  final ActionType        actionType;
  final ActionSource      source;
  final String?           beforeSnapshotId;
  final String?           afterSnapshotId;
  final String?           description;
  final HistoryEntryStatus status;
}

// ==================================================
// UNDO / REDO RESULT
// Returned by undo() and redo() so callers can act on the outcome
// without catching exceptions.
// ==================================================

sealed class UndoResult {}

final class UndoSuccess extends UndoResult {
  UndoSuccess({
    required this.restoredEntry,
    required this.stepsApplied,
  });
  final HistoryEntry restoredEntry;
  final int          stepsApplied;
}

final class UndoFailure extends UndoResult {
  UndoFailure({required this.reason, this.stepsApplied = 0});
  final String reason;
  final int    stepsApplied;
}

sealed class RedoResult {}

final class RedoSuccess extends RedoResult {
  RedoSuccess({
    required this.restoredEntry,
    required this.stepsApplied,
  });
  final HistoryEntry restoredEntry;
  final int          stepsApplied;
}

final class RedoFailure extends RedoResult {
  RedoFailure({required this.reason, this.stepsApplied = 0});
  final String reason;
  final int    stepsApplied;
}

// ==================================================
// HISTORY REPORT
// Point-in-time snapshot of the history system state.
// ==================================================

class HistoryReport {
  const HistoryReport({
    required this.generatedAt,
    required this.undoDepth,
    required this.redoDepth,
    required this.totalEntries,
    required this.evictedCount,
    required this.maxHistorySize,
    required this.timeline,
    required this.oldestEntry,
    required this.newestEntry,
  });

  final DateTime       generatedAt;
  final int            undoDepth;
  final int            redoDepth;
  final int            totalEntries;
  final int            evictedCount;
  final int            maxHistorySize;
  final List<HistoryEntry> timeline;
  final HistoryEntry?  oldestEntry;
  final HistoryEntry?  newestEntry;

  bool get canUndo => undoDepth > 0;
  bool get canRedo => redoDepth > 0;

  @override
  String toString() =>
      'HistoryReport(undoDepth: $undoDepth, redoDepth: $redoDepth, '
      'total: $totalEntries, evicted: $evictedCount)';
}

// ==================================================
// HISTORY MANAGER CONFIGURATION
// ==================================================

class HistoryManagerConfig {
  const HistoryManagerConfig({
    this.maxHistorySize    = 100,
    this.maxRedoSize       = 50,
    this.autoTrimOnPush    = true,
    this.snapshotEveryStep = true,
    this.guardEnabled      = true,
  });

  /// Maximum number of entries kept on the undo stack.
  final int maxHistorySize;

  /// Maximum number of entries kept on the redo stack.
  final int maxRedoSize;

  /// Automatically call trimHistory() whenever a push exceeds the cap.
  final bool autoTrimOnPush;

  /// Request a snapshot before every registered action.
  final bool snapshotEveryStep;

  /// Route undo/redo through HistoryGuard before executing.
  final bool guardEnabled;
}

// ==================================================
// HISTORY MANAGER
// The single source of truth for all undo/redo state in Z-CANVAS.
// ==================================================

class HistoryManager {
  HistoryManager({
    required SnapshotEngineInterface  snapshotEngine,
    required RecoveryEngineInterface  recoveryEngine,
    required HistoryGuardInterface    historyGuard,
    HistoryManagerConfig config = const HistoryManagerConfig(),
  })  : _snapshot  = snapshotEngine,
        _recovery  = recoveryEngine,
        _guard     = historyGuard,
        _config    = config;

  final SnapshotEngineInterface  _snapshot;
  final RecoveryEngineInterface  _recovery;
  final HistoryGuardInterface    _guard;
  final HistoryManagerConfig     _config;

  // — Undo stack: index 0 = oldest, last = most recent —
  final List<HistoryEntry> _undoStack = [];

  // — Redo stack: index 0 = oldest redo, last = most recently undone —
  final List<HistoryEntry> _redoStack = [];

  // — Full chronological timeline (read-only view, never modified) —
  final List<HistoryEntry> _timeline = [];

  // — Monotonic history-id counter —
  int _historyIdSeq = 0;

  // — Count of entries evicted by trimHistory —
  int _evictedCount = 0;

  // ==================================================
  // PUBLIC API — mandatory functions per contract
  // ==================================================

  // --------------------------------------------------
  // registerAction()
  // Entry point called by Phase-14 / EditorController after every
  // successful execution. Creates the entry, guards it, pushes it,
  // clears the redo stack, trims if needed.
  // Returns the committed HistoryEntry or null if the guard rejected it.
  // --------------------------------------------------

  Future<HistoryEntry?> registerAction(
      HistoryRegistrationParams params) async {
    final entry = createHistoryEntry(params);

    // Guard check — reject before any stack mutation.
    if (_config.guardEnabled) {
      final allowed = await _guard.canRegister(entry);
      if (!allowed) {
        _log('registerAction: guard rejected entry ${entry.historyId} '
            '(action: ${entry.actionType}).');
        return null;
      }
    }

    pushUndoEntry(entry);
    clearRedoStack();

    if (_config.autoTrimOnPush) trimHistory();

    _timeline.add(entry);
    _log('registerAction: committed ${entry.historyId} '
        '(action: ${entry.actionType}, undoDepth: ${_undoStack.length}).');

    return entry;
  }

  // --------------------------------------------------
  // createHistoryEntry()
  // Constructs a new immutable HistoryEntry from [params].
  // Does NOT push to any stack — callers do that explicitly.
  // --------------------------------------------------

  HistoryEntry createHistoryEntry(HistoryRegistrationParams params) {
    _historyIdSeq++;
    return HistoryEntry(
      historyId:        'hist_${_historyIdSeq.toString().padLeft(6, "0")}',
      actionId:         params.actionId,
      actionType:       params.actionType,
      timestamp:        DateTime.now().toUtc(),
      source:           params.source,
      status:           params.status,
      beforeSnapshotId: params.beforeSnapshotId,
      afterSnapshotId:  params.afterSnapshotId,
      description:      params.description,
    );
  }

  // --------------------------------------------------
  // pushUndoEntry()
  // Pushes a committed entry onto the top of the undo stack.
  // Trims if the stack exceeds the configured maximum.
  // --------------------------------------------------

  void pushUndoEntry(HistoryEntry entry) {
    _undoStack.add(entry);
    if (_config.autoTrimOnPush &&
        _undoStack.length > _config.maxHistorySize) {
      trimHistory();
    }
  }

  // --------------------------------------------------
  // pushRedoEntry()
  // Pushes an undone entry onto the redo stack.
  // --------------------------------------------------

  void pushRedoEntry(HistoryEntry entry) {
    _redoStack.add(entry);
    if (_redoStack.length > _config.maxRedoSize) {
      _redoStack.removeAt(0); // evict oldest redo entry silently
    }
  }

  // --------------------------------------------------
  // clearRedoStack()
  // Removes all entries from the redo stack.
  // Called whenever a new action is registered (forward branch taken).
  // Also cleans up orphaned redo snapshots.
  // --------------------------------------------------

  void clearRedoStack() {
    if (_redoStack.isEmpty) return;
    final count = _redoStack.length;
    _scheduleRedoSnapshotCleanup(List.of(_redoStack));
    _redoStack.clear();
    _log('clearRedoStack: removed $count redo entries.');
  }

  // --------------------------------------------------
  // undo()
  // Pops the top [steps] entries from the undo stack,
  // guards each one, delegates restoration to RecoveryEngine,
  // and pushes the reversed entry to the redo stack.
  // --------------------------------------------------

  Future<UndoResult> undo({int steps = 1}) async {
    if (_undoStack.isEmpty) {
      return UndoFailure(reason: 'Nothing to undo — undo stack is empty.');
    }
    if (steps < 1) {
      return UndoFailure(reason: 'undo: steps must be ≥ 1 (got $steps).');
    }

    final effectiveSteps = steps.clamp(1, _undoStack.length);
    int applied = 0;
    HistoryEntry? lastRestored;

    for (var i = 0; i < effectiveSteps; i++) {
      if (_undoStack.isEmpty) break;

      final entry = _undoStack.last;

      // Guard check.
      if (_config.guardEnabled) {
        final safe = await _guard.canUndo(entry);
        if (!safe) {
          _log('undo: guard blocked step ${i + 1} for entry '
              '${entry.historyId}.');
          break;
        }
      }

      // Determine which snapshot to restore.
      final targetSnapshotId = entry.beforeSnapshotId;
      if (targetSnapshotId == null) {
        _log('undo: entry ${entry.historyId} has no beforeSnapshotId — '
            'falling back to recoverLatestSafeState.');
        final fallback = await _recovery.recoverLatestSafeState(
            sessionId: 'undo_${entry.historyId}');
        if (fallback != null) {
          return UndoFailure(
              reason: 'undo fallback failed: $fallback',
              stepsApplied: applied);
        }
      } else {
        final restoreError = await _recovery.restoreSnapshot(
            targetSnapshotId,
            sessionId: 'undo_${entry.historyId}');
        if (restoreError != null) {
          return UndoFailure(
              reason: 'undo: restore failed — $restoreError',
              stepsApplied: applied);
        }
      }

      // Transition entry status and move between stacks.
      final undoneEntry = entry.copyWith(status: HistoryEntryStatus.undone);
      _undoStack.removeLast();
      pushRedoEntry(undoneEntry);
      _updateTimeline(undoneEntry);

      lastRestored = undoneEntry;
      applied++;
      _log('undo: step ${i + 1} — restored ${entry.historyId} '
          '(action: ${entry.actionType}).');
    }

    if (lastRestored == null) {
      return UndoFailure(
          reason: 'undo: no steps could be applied.',
          stepsApplied: 0);
    }
    return UndoSuccess(restoredEntry: lastRestored, stepsApplied: applied);
  }

  // --------------------------------------------------
  // redo()
  // Pops the top [steps] entries from the redo stack,
  // guards each one, delegates restoration to RecoveryEngine
  // (restores the afterSnapshot), and pushes back to undo stack.
  // --------------------------------------------------

  Future<RedoResult> redo({int steps = 1}) async {
    if (_redoStack.isEmpty) {
      return RedoFailure(reason: 'Nothing to redo — redo stack is empty.');
    }
    if (steps < 1) {
      return RedoFailure(reason: 'redo: steps must be ≥ 1 (got $steps).');
    }

    final effectiveSteps = steps.clamp(1, _redoStack.length);
    int applied = 0;
    HistoryEntry? lastRestored;

    for (var i = 0; i < effectiveSteps; i++) {
      if (_redoStack.isEmpty) break;

      final entry = _redoStack.last;

      // Guard check.
      if (_config.guardEnabled) {
        final safe = await _guard.canRedo(entry);
        if (!safe) {
          _log('redo: guard blocked step ${i + 1} for entry '
              '${entry.historyId}.');
          break;
        }
      }

      final targetSnapshotId = entry.afterSnapshotId;
      if (targetSnapshotId == null) {
        _log('redo: entry ${entry.historyId} has no afterSnapshotId — '
            'falling back to recoverLatestSafeState.');
        final fallback = await _recovery.recoverLatestSafeState(
            sessionId: 'redo_${entry.historyId}');
        if (fallback != null) {
          return RedoFailure(
              reason: 'redo fallback failed: $fallback',
              stepsApplied: applied);
        }
      } else {
        final restoreError = await _recovery.restoreSnapshot(
            targetSnapshotId,
            sessionId: 'redo_${entry.historyId}');
        if (restoreError != null) {
          return RedoFailure(
              reason: 'redo: restore failed — $restoreError',
              stepsApplied: applied);
        }
      }

      final redoneEntry = entry.copyWith(status: HistoryEntryStatus.redone);
      _redoStack.removeLast();
      pushUndoEntry(redoneEntry);
      _updateTimeline(redoneEntry);

      lastRestored = redoneEntry;
      applied++;
      _log('redo: step ${i + 1} — re-applied ${entry.historyId} '
          '(action: ${entry.actionType}).');
    }

    if (lastRestored == null) {
      return RedoFailure(
          reason: 'redo: no steps could be applied.',
          stepsApplied: 0);
    }
    return RedoSuccess(restoredEntry: lastRestored, stepsApplied: applied);
  }

  // --------------------------------------------------
  // trimHistory()
  // Evicts the oldest entries from the undo stack when it exceeds
  // [maxHistorySize]. Schedules orphaned before-snapshots for removal.
  // --------------------------------------------------

  void trimHistory() {
    if (_undoStack.length <= _config.maxHistorySize) return;

    final excess = _undoStack.length - _config.maxHistorySize;
    final evicted = _undoStack.sublist(0, excess);
    _undoStack.removeRange(0, excess);
    _evictedCount += excess;

    // Mark evicted entries in the timeline.
    for (final e in evicted) {
      _updateTimeline(e.copyWith(status: HistoryEntryStatus.evicted));
    }

    // Orphaned snapshots from evicted entries can now be removed.
    _scheduleEvictedSnapshotCleanup(evicted);

    _log('trimHistory: evicted $excess entries '
        '(total evicted: $_evictedCount, '
        'undoDepth now: ${_undoStack.length}).');
  }

  // --------------------------------------------------
  // clearHistory()
  // Wipes all stacks and the timeline. Used on new document open
  // or session reset. Schedules all snapshot IDs for cleanup.
  // --------------------------------------------------

  void clearHistory() {
    final allEntries = [
      ..._undoStack,
      ..._redoStack,
    ];
    _undoStack.clear();
    _redoStack.clear();
    _timeline.clear();
    _evictedCount = 0;
    _historyIdSeq = 0;
    _scheduleEvictedSnapshotCleanup(allEntries);
    _log('clearHistory: all stacks and timeline cleared.');
  }

  // --------------------------------------------------
  // generateHistoryReport()
  // Returns an immutable point-in-time view of the history state.
  // --------------------------------------------------

  HistoryReport generateHistoryReport() {
    final timeline = List<HistoryEntry>.unmodifiable(_timeline);
    return HistoryReport(
      generatedAt:    DateTime.now().toUtc(),
      undoDepth:      _undoStack.length,
      redoDepth:      _redoStack.length,
      totalEntries:   _timeline.length,
      evictedCount:   _evictedCount,
      maxHistorySize: _config.maxHistorySize,
      timeline:       timeline,
      oldestEntry:    _undoStack.isNotEmpty ? _undoStack.first : null,
      newestEntry:    _undoStack.isNotEmpty ? _undoStack.last  : null,
    );
  }

  // ==================================================
  // READ-ONLY ACCESSORS
  // ==================================================

  /// Whether there is at least one entry that can be undone.
  bool get canUndo => _undoStack.isNotEmpty;

  /// Whether there is at least one entry that can be redone.
  bool get canRedo => _redoStack.isNotEmpty;

  /// Current depth of the undo stack.
  int get undoDepth => _undoStack.length;

  /// Current depth of the redo stack.
  int get redoDepth => _redoStack.length;

  /// Immutable ordered timeline of all registered and transitioned entries.
  List<HistoryEntry> get timeline => List.unmodifiable(_timeline);

  /// The entry that would be undone by the next undo() call, or null.
  HistoryEntry? get peekUndo =>
      _undoStack.isNotEmpty ? _undoStack.last : null;

  /// The entry that would be redone by the next redo() call, or null.
  HistoryEntry? get peekRedo =>
      _redoStack.isNotEmpty ? _redoStack.last : null;

  // ==================================================
  // PRIVATE HELPERS
  // ==================================================

  /// Updates the most recent timeline record for [entry.historyId].
  /// If no existing record found, appends the entry as a new record.
  void _updateTimeline(HistoryEntry entry) {
    final idx = _timeline.indexWhere((e) => e.historyId == entry.historyId);
    if (idx >= 0) {
      _timeline[idx] = entry;
    } else {
      _timeline.add(entry);
    }
  }

  /// Schedules orphaned redo-stack snapshot IDs for removal.
  /// Fire-and-forget — failures are logged but non-blocking.
  void _scheduleRedoSnapshotCleanup(List<HistoryEntry> entries) {
    for (final entry in entries) {
      final sid = entry.afterSnapshotId;
      if (sid != null) {
        _snapshot.removeSnapshot(sid).catchError((e) {
          _log('WARNING: could not remove redo snapshot $sid: $e');
        });
      }
    }
  }

  /// Schedules evicted or cleared entry snapshot IDs for removal.
  void _scheduleEvictedSnapshotCleanup(List<HistoryEntry> entries) {
    for (final entry in entries) {
      for (final sid in [entry.beforeSnapshotId, entry.afterSnapshotId]) {
        if (sid != null) {
          _snapshot.removeSnapshot(sid).catchError((e) {
            _log('WARNING: could not remove evicted snapshot $sid: $e');
          });
        }
      }
    }
  }

  void _log(String message) {
    // ignore: avoid_print
    print('[HistoryManager] $message');
  }
}

// ==================================================
// NULL IMPLEMENTATIONS
// Safe no-op providers for testing and development.
// ==================================================

/// Snapshot engine that generates unique IDs but does nothing.
class NullSnapshotEngine implements SnapshotEngineInterface {
  int _seq = 0;
  @override Future<String> createSnapshot({required String sessionId}) async =>
      'null_snap_${++_seq}';
  @override Future<bool>   validateSnapshot(String id) async => true;
  @override Future<void>   removeSnapshot(String id)   async {}
}

/// Recovery engine that reports success without restoring anything.
class NullRecoveryEngine implements RecoveryEngineInterface {
  @override Future<String?> restoreSnapshot(String id,
      {required String sessionId}) async => null;
  @override Future<String?> recoverLatestSafeState(
      {required String sessionId}) async => null;
}

/// Guard that allows every operation unconditionally.
class NullHistoryGuard implements HistoryGuardInterface {
  const NullHistoryGuard();
  @override Future<bool> canUndo(HistoryEntry e)     async => true;
  @override Future<bool> canRedo(HistoryEntry e)     async => true;
  @override Future<bool> canRegister(HistoryEntry e) async => true;
}

/// Convenience factory — returns a HistoryManager wired with all null deps.
HistoryManager buildNullHistoryManager({
  HistoryManagerConfig config = const HistoryManagerConfig(),
}) =>
    HistoryManager(
      snapshotEngine: NullSnapshotEngine(),
      recoveryEngine: NullRecoveryEngine(),
      historyGuard:   const NullHistoryGuard(),
      config:         config,
    );

// ==================================================
// END OF core/history/history_manager.dart
// Z-CANVAS — PHASE-15 — MASTER HISTORY ORCHESTRATOR
// Powered by Zynquar
// ==================================================
